import React, { useState, useEffect } from 'react';
import {
  X,
  Send,
  Copy,
  Check,
  Calendar,
  Phone,
  MessageSquare,
  Sparkles,
  ExternalLink,
  CreditCard,
  Clock,
  User,
  ShieldCheck,
  ArrowRight,
  Info,
} from 'lucide-react';
import { PersonLedger, Transaction } from '../../types';
import { formatINR } from '../../utils/formatters';
import {
  WhatsAppTemplateType,
  cleanPhoneNumber,
  generateWhatsAppMessage,
  buildWhatsAppRedirectUrl,
  formatFriendlyDueDate,
} from '../../utils/whatsapp';

interface WhatsAppReminderModalProps {
  isOpen: boolean;
  onClose: () => void;
  personLedger: PersonLedger | null;
  defaultUpiId?: string;
  onUpdatePhoneAndDueDate?: (personName: string, phone: string, dueDate: string) => void;
}

export const WhatsAppReminderModal: React.FC<WhatsAppReminderModalProps> = ({
  isOpen,
  onClose,
  personLedger,
  defaultUpiId = '',
  onUpdatePhoneAndDueDate,
}) => {
  if (!isOpen || !personLedger) return null;

  // Form states
  const [phoneNumber, setPhoneNumber] = useState<string>(personLedger.phone || '');
  const [dueDate, setDueDate] = useState<string>(() => {
    if (personLedger.dueDate) return personLedger.dueDate;
    // Default to 7 days from today if not set
    const d = new Date();
    d.setDate(d.getDate() + 7);
    return d.toISOString().split('T')[0];
  });
  const [upiId, setUpiId] = useState<string>(defaultUpiId);
  const [template, setTemplate] = useState<WhatsAppTemplateType>('friendly');
  const [customNote, setCustomNote] = useState<string>('');
  const [isCustomEditing, setIsCustomEditing] = useState<boolean>(false);
  const [customMessageOverride, setCustomMessageOverride] = useState<string>('');
  const [isCopied, setIsCopied] = useState<boolean>(false);
  const [hasSent, setHasSent] = useState<boolean>(false);

  // Sync when personLedger changes
  useEffect(() => {
    if (personLedger) {
      setPhoneNumber(personLedger.phone || '');
      if (personLedger.dueDate) {
        setDueDate(personLedger.dueDate);
      } else {
        const d = new Date();
        d.setDate(d.getDate() + 7);
        setDueDate(d.toISOString().split('T')[0]);
      }
      setIsCustomEditing(false);
      setCustomMessageOverride('');
      setIsCopied(false);
      setHasSent(false);
    }
  }, [personLedger]);

  // Generate draft message based on current inputs
  const autoGeneratedMessage = generateWhatsAppMessage({
    personName: personLedger.name,
    netBalance: personLedger.netBalance,
    dueDate,
    upiId,
    customNote,
    template,
    totalLent: personLedger.totalLent,
    totalBorrowed: personLedger.totalBorrowed,
  });

  const finalMessage = isCustomEditing ? customMessageOverride : autoGeneratedMessage;
  const cleanedPhone = cleanPhoneNumber(phoneNumber);
  const whatsappUrl = buildWhatsAppRedirectUrl(phoneNumber, finalMessage);

  const isReceivable = personLedger.netBalance > 0;
  const isPayable = personLedger.netBalance < 0;

  // Quick Due Date Presets
  const handleSetPresetDate = (daysFromNow: number) => {
    const d = new Date();
    d.setDate(d.getDate() + daysFromNow);
    const dateStr = d.toISOString().split('T')[0];
    setDueDate(dateStr);
    if (isCustomEditing) {
      setIsCustomEditing(false);
    }
  };

  const handleSetMonthEnd = () => {
    const now = new Date();
    const lastDay = new Date(now.getFullYear(), now.getMonth() + 1, 0);
    const dateStr = lastDay.toISOString().split('T')[0];
    setDueDate(dateStr);
    if (isCustomEditing) {
      setIsCustomEditing(false);
    }
  };

  const handleCopyMessage = () => {
    navigator.clipboard.writeText(finalMessage);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2500);
  };

  const handleSendToWhatsApp = () => {
    // Optionally notify parent to save phone/dueDate
    if (onUpdatePhoneAndDueDate) {
      onUpdatePhoneAndDueDate(personLedger.name, phoneNumber, dueDate);
    }

    // Open WhatsApp in new tab / application
    window.open(whatsappUrl, '_blank', 'noopener,noreferrer');
    setHasSent(true);
  };

  return (
    <div className="fixed inset-0 z-60 flex items-center justify-center overflow-y-auto bg-slate-900/70 p-3 sm:p-4 md:p-6 backdrop-blur-xs">
      <div
        id="whatsapp-reminder-modal"
        className="relative w-full max-w-4xl rounded-2xl bg-white shadow-2xl border border-slate-200 overflow-hidden flex flex-col max-h-[92vh] animate-in fade-in zoom-in-95 duration-200"
      >
        {/* Header with WhatsApp Brand Identity */}
        <div className="flex items-center justify-between border-b border-emerald-100 px-6 py-4 bg-gradient-to-r from-emerald-600 to-teal-700 text-white shrink-0">
          <div className="flex items-center gap-3">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-white/20 backdrop-blur-md shadow-inner text-white">
              <MessageSquare className="h-5 w-5 fill-white/20" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-base font-bold font-heading">
                  WhatsApp Khata Reminder
                </h3>
                <span className="text-[10px] font-extrabold uppercase px-2 py-0.5 rounded-full bg-white/20 text-white tracking-wider border border-white/30">
                  Direct Redirect
                </span>
              </div>
              <p className="text-xs text-emerald-100">
                Drafts message & opens WhatsApp with prefilled search for {personLedger.name}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="rounded-lg p-1.5 text-white/80 hover:bg-white/10 hover:text-white transition-colors cursor-pointer"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Content Body - 2 Column Layout */}
        <div className="flex-1 overflow-y-auto p-5 sm:p-6 space-y-4 bg-slate-50/50">
          {/* Top Info Banner */}
          <div className={`p-3.5 rounded-xl border flex items-center justify-between gap-4 shrink-0 ${
            isReceivable
              ? 'bg-emerald-50/80 border-emerald-200 text-emerald-950'
              : isPayable
              ? 'bg-amber-50/80 border-amber-200 text-amber-950'
              : 'bg-slate-100 border-slate-200 text-slate-800'
          }`}>
            <div>
              <div className="flex items-center gap-2">
                <span className="text-xs font-semibold text-slate-600">Contact:</span>
                <span className="text-sm font-bold text-slate-900">{personLedger.name}</span>
                <span className={`text-[10px] font-bold px-2 py-0.5 rounded uppercase tracking-wider ${
                  isReceivable
                    ? 'bg-emerald-600 text-white'
                    : isPayable
                    ? 'bg-amber-600 text-white'
                    : 'bg-slate-400 text-white'
                }`}>
                  {isReceivable ? 'Receivable (They owe you)' : isPayable ? 'Payable (You owe)' : 'Settled'}
                </span>
              </div>
              <p className="text-xs text-slate-500 mt-0.5">
                {isReceivable
                  ? `Friendly reminder for ${personLedger.name} to settle pending dues with due date.`
                  : isPayable
                  ? `Payment intimation confirming you will settle the dues soon.`
                  : 'Ledger is settled. Send a thank-you note.'}
              </p>
            </div>

            <div className="text-right shrink-0">
              <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block">
                Outstanding Balance
              </span>
              <span className={`text-xl font-bold font-heading ${
                isReceivable ? 'text-emerald-700' : isPayable ? 'text-rose-700' : 'text-slate-700'
              }`}>
                {formatINR(Math.abs(personLedger.netBalance))}
              </span>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-5 items-start">
            {/* Left Column: Form Controls & Template Tone Selector */}
            <div className="space-y-4">
              {/* Form Controls Grid */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 bg-white p-4 rounded-xl border border-slate-200 shadow-2xs">
                {/* 1. Phone Number */}
                <div>
                  <label className="text-xs font-bold text-slate-700 flex items-center gap-1.5 mb-1">
                    <Phone className="h-3.5 w-3.5 text-emerald-600" />
                    <span>WhatsApp Phone</span>
                  </label>
                  <div className="relative">
                    <input
                      type="text"
                      value={phoneNumber}
                      onChange={(e) => setPhoneNumber(e.target.value)}
                      placeholder="+91 98765 43210 or 9876543210"
                      className="w-full text-xs rounded-lg border border-slate-200 px-3 py-2 pl-7.5 focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500 outline-none transition-all font-mono bg-slate-50/60"
                    />
                    <span className="absolute left-2.5 top-2 text-slate-400 text-xs">📞</span>
                  </div>
                  <p className="text-[10px] text-slate-400 mt-1">
                    {cleanedPhone ? (
                      <span className="text-emerald-600 font-semibold">
                        ✓ Targets: +{cleanedPhone}
                      </span>
                    ) : (
                      <span>Opens chat search in WhatsApp</span>
                    )}
                  </p>
                </div>

                {/* 2. Due Date */}
                <div>
                  <label className="text-xs font-bold text-slate-700 flex items-center justify-between mb-1">
                    <span className="flex items-center gap-1">
                      <Calendar className="h-3.5 w-3.5 text-indigo-600" />
                      <span>Due Date</span>
                    </span>
                    <span className="text-[9px] font-bold text-indigo-600 bg-indigo-50 px-1 py-0.2 rounded">
                      {formatFriendlyDueDate(dueDate)}
                    </span>
                  </label>
                  <input
                    type="date"
                    value={dueDate}
                    onChange={(e) => {
                      setDueDate(e.target.value);
                      if (isCustomEditing) setIsCustomEditing(false);
                    }}
                    className="w-full text-xs rounded-lg border border-slate-200 px-3 py-2 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 outline-none transition-all bg-slate-50/60"
                  />

                  {/* Quick Due Date Presets */}
                  <div className="flex items-center gap-1 mt-1 overflow-x-auto">
                    <span className="text-[9px] text-slate-400 font-bold uppercase mr-0.5 shrink-0">Quick:</span>
                    <button
                      type="button"
                      onClick={() => handleSetPresetDate(1)}
                      className="text-[9px] font-semibold px-1.5 py-0.5 rounded bg-slate-100 hover:bg-slate-200 text-slate-700 transition-colors shrink-0 cursor-pointer"
                    >
                      Tomorrow
                    </button>
                    <button
                      type="button"
                      onClick={() => handleSetPresetDate(3)}
                      className="text-[9px] font-semibold px-1.5 py-0.5 rounded bg-slate-100 hover:bg-slate-200 text-slate-700 transition-colors shrink-0 cursor-pointer"
                    >
                      +3 Days
                    </button>
                    <button
                      type="button"
                      onClick={() => handleSetPresetDate(7)}
                      className="text-[9px] font-semibold px-1.5 py-0.5 rounded bg-slate-100 hover:bg-slate-200 text-slate-700 transition-colors shrink-0 cursor-pointer"
                    >
                      +1 Wk
                    </button>
                    <button
                      type="button"
                      onClick={handleSetMonthEnd}
                      className="text-[9px] font-semibold px-1.5 py-0.5 rounded bg-slate-100 hover:bg-slate-200 text-slate-700 transition-colors shrink-0 cursor-pointer"
                    >
                      End Mo
                    </button>
                  </div>
                </div>

                {/* 3. Optional UPI ID */}
                <div>
                  <label className="text-xs font-bold text-slate-700 flex items-center gap-1.5 mb-1">
                    <CreditCard className="h-3.5 w-3.5 text-slate-600" />
                    <span>Your UPI ID (Optional)</span>
                  </label>
                  <input
                    type="text"
                    value={upiId}
                    onChange={(e) => {
                      setUpiId(e.target.value);
                      if (isCustomEditing) setIsCustomEditing(false);
                    }}
                    placeholder="e.g. name@okhdfcbank"
                    className="w-full text-xs rounded-lg border border-slate-200 px-3 py-2 focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500 outline-none transition-all bg-slate-50/60"
                  />
                </div>

                {/* 4. Optional Custom Memo / Purpose */}
                <div>
                  <label className="text-xs font-bold text-slate-700 flex items-center gap-1.5 mb-1">
                    <Sparkles className="h-3.5 w-3.5 text-amber-500" />
                    <span>Custom Note (Optional)</span>
                  </label>
                  <input
                    type="text"
                    value={customNote}
                    onChange={(e) => {
                      setCustomNote(e.target.value);
                      if (isCustomEditing) setIsCustomEditing(false);
                    }}
                    placeholder="e.g. Car repair split, Trip hotel"
                    className="w-full text-xs rounded-lg border border-slate-200 px-3 py-2 focus:border-amber-500 focus:ring-1 focus:ring-amber-500 outline-none transition-all bg-slate-50/60"
                  />
                </div>
              </div>

              {/* Template Style Selector */}
              <div>
                <div className="flex items-center justify-between mb-2">
                  <label className="text-xs font-bold text-slate-700 uppercase tracking-wider">
                    Select Message Tone & Format
                  </label>
                  {isCustomEditing && (
                    <button
                      onClick={() => {
                        setIsCustomEditing(false);
                        setCustomMessageOverride('');
                      }}
                      className="text-[11px] text-indigo-600 hover:text-indigo-800 font-semibold cursor-pointer"
                    >
                      ↺ Reset Auto
                    </button>
                  )}
                </div>

                <div className="grid grid-cols-2 gap-2">
                  <button
                    type="button"
                    onClick={() => {
                      setTemplate('friendly');
                      setIsCustomEditing(false);
                    }}
                    className={`p-2.5 rounded-xl border text-left transition-all cursor-pointer ${
                      template === 'friendly' && !isCustomEditing
                        ? 'border-emerald-600 bg-emerald-50/50 text-emerald-950 ring-1 ring-emerald-500 font-bold'
                        : 'border-slate-200 bg-white hover:bg-slate-50 text-slate-700'
                    }`}
                  >
                    <span className="text-base block mb-0.5">✨</span>
                    <div className="text-xs font-bold">1. Friendly</div>
                    <div className="text-[10px] text-slate-500">Warm & polite with emojis</div>
                  </button>

                  <button
                    type="button"
                    onClick={() => {
                      setTemplate('formal');
                      setIsCustomEditing(false);
                    }}
                    className={`p-2.5 rounded-xl border text-left transition-all cursor-pointer ${
                      template === 'formal' && !isCustomEditing
                        ? 'border-emerald-600 bg-emerald-50/50 text-emerald-950 ring-1 ring-emerald-500 font-bold'
                        : 'border-slate-200 bg-white hover:bg-slate-50 text-slate-700'
                    }`}
                  >
                    <span className="text-base block mb-0.5">📋</span>
                    <div className="text-xs font-bold">2. Formal Notice</div>
                    <div className="text-[10px] text-slate-500">Official due date alert</div>
                  </button>

                  <button
                    type="button"
                    onClick={() => {
                      setTemplate('quick_upi');
                      setIsCustomEditing(false);
                    }}
                    className={`p-2.5 rounded-xl border text-left transition-all cursor-pointer ${
                      template === 'quick_upi' && !isCustomEditing
                        ? 'border-emerald-600 bg-emerald-50/50 text-emerald-950 ring-1 ring-emerald-500 font-bold'
                        : 'border-slate-200 bg-white hover:bg-slate-50 text-slate-700'
                    }`}
                  >
                    <span className="text-base block mb-0.5">⚡</span>
                    <div className="text-xs font-bold">3. Quick UPI</div>
                    <div className="text-[10px] text-slate-500">Short 1-line prompt</div>
                  </button>

                  <button
                    type="button"
                    onClick={() => {
                      setTemplate('detailed_statement');
                      setIsCustomEditing(false);
                    }}
                    className={`p-2.5 rounded-xl border text-left transition-all cursor-pointer ${
                      template === 'detailed_statement' && !isCustomEditing
                        ? 'border-emerald-600 bg-emerald-50/50 text-emerald-950 ring-1 ring-emerald-500 font-bold'
                        : 'border-slate-200 bg-white hover:bg-slate-50 text-slate-700'
                    }`}
                  >
                    <span className="text-base block mb-0.5">📊</span>
                    <div className="text-xs font-bold">4. Statement</div>
                    <div className="text-[10px] text-slate-500">Full ledger breakdown</div>
                  </button>
                </div>
              </div>
            </div>

            {/* Right Column: Live WhatsApp Chat Bubble Preview & Editor */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold text-slate-700 flex items-center gap-1.5">
                  <MessageSquare className="h-3.5 w-3.5 text-emerald-600" />
                  <span>WhatsApp Message Preview</span>
                </span>
                <span className="text-[11px] text-slate-500">
                  Directly editable below
                </span>
              </div>

              {/* Simulated WhatsApp Wallpaper Container */}
              <div className="rounded-2xl bg-[#ECE5DD] border border-[#d6cec5] p-4 shadow-inner">
                {/* WhatsApp Message Bubble */}
                <div className="relative w-full bg-[#DCF8C6] border border-[#c4eab0] rounded-2xl rounded-tr-xs p-3.5 text-xs text-slate-800 shadow-xs space-y-2">
                  <textarea
                    value={finalMessage}
                    onChange={(e) => {
                      setIsCustomEditing(true);
                      setCustomMessageOverride(e.target.value);
                    }}
                    rows={9}
                    className="w-full bg-transparent border-none outline-none resize-none text-xs text-slate-900 leading-relaxed font-sans"
                    placeholder="Type or customize your WhatsApp message..."
                  />

                  <div className="flex items-center justify-between pt-1 border-t border-emerald-200/60 text-[10px] text-slate-500">
                    <span className="italic">
                      {isCustomEditing ? '✎ Custom edited' : '✨ Auto-generated draft'}
                    </span>
                    <div className="flex items-center gap-1 font-semibold text-emerald-800">
                      <span>
                        {new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                      </span>
                      <span className="text-blue-500 font-bold">✓✓</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Modal Footer with Direct Actions */}
        <div className="border-t border-slate-200 bg-white px-6 py-4 flex flex-col sm:flex-row items-center justify-between gap-3 shrink-0">
          <div className="flex items-center gap-2 text-xs text-slate-500">
            <ShieldCheck className="h-4 w-4 text-emerald-600 shrink-0" />
            <span className="text-[11px]">
              No API keys required. Direct browser deep-link to WhatsApp Web / App.
            </span>
          </div>

          <div className="flex items-center gap-2.5 w-full sm:w-auto">
            {/* Copy Button */}
            <button
              type="button"
              onClick={handleCopyMessage}
              className="flex items-center justify-center gap-1.5 px-4 py-2.5 rounded-xl border border-slate-200 bg-white hover:bg-slate-50 text-slate-700 text-xs font-bold transition-all cursor-pointer shadow-2xs shrink-0"
              title="Copy message to clipboard"
            >
              {isCopied ? (
                <>
                  <Check className="h-4 w-4 text-emerald-600" />
                  <span className="text-emerald-700">Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="h-4 w-4 text-slate-500" />
                  <span>Copy Text</span>
                </>
              )}
            </button>

            {/* Direct Send via WhatsApp Button */}
            <button
              type="button"
              id="btn-send-whatsapp-modal"
              onClick={handleSendToWhatsApp}
              className="flex-1 sm:flex-initial flex items-center justify-center gap-2 px-6 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 active:scale-98 text-white text-xs font-bold uppercase tracking-wider shadow-md hover:shadow-lg transition-all cursor-pointer group"
            >
              <Send className="h-4 w-4 transform group-hover:translate-x-0.5 transition-transform" />
              <span>Send via WhatsApp</span>
              <ExternalLink className="h-3.5 w-3.5 opacity-80" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
