import {
  UserProfile,
  VacationPlan,
  DateToRemember,
  MonthlyFestivalArt,
} from '../types';

export const DEFAULT_USER_PROFILE: UserProfile = {
  id: 'usr_kaiwalya_01',
  name: 'Kaiwalya',
  email: 'kaiwalya.2501@gmail.com',
  phone: '',
  birthdate: '',
  birthdayFormatted: '',
  bio: 'Building long-term wealth, vibrant vitality, and atomic daily habits.',
  avatar: '👑',
  city: 'Mumbai',
  country: 'India',
  occupation: '',
  bloodGroup: '',
  emergencyContactName: '',
  emergencyContactPhone: '',
  currencySymbol: '₹',
  monthlySavingsTarget: 0,
  emergencyFundTarget: 0,
  targetWeightKg: 0,
  dailyWaterGoalMl: 3000,
  targetDailyWaterMl: 3000,
  targetDailySleepHours: 8,
  favoriteFestivals: [
    'Ganesh Chaturthi',
    'Diwali',
    'Holi',
    'Navratri',
    'Raksha Bandhan',
    'Makar Sankranti',
  ],
  themePreference: 'indigo',
  updatedAt: new Date().toISOString(),
};

// Clean 100% Fresh Start: Zero Sample Dates
export const DEFAULT_DATES_TO_REMEMBER: DateToRemember[] = [];

// Clean 100% Fresh Start: Zero Sample Vacations
export const DEFAULT_VACATIONS: VacationPlan[] = [];

export const MONTHLY_FESTIVAL_ARTS: MonthlyFestivalArt[] = [
  {
    monthIndex: 0,
    monthName: 'January',
    heroTitle: 'Makar Sankranti & Republic Day',
    heroSubtitle: 'Sun transit, soaring colorful kites, harvest warmth & patriotic tricolor pride.',
    culturalQuote: '“Tilgul ghya, aani god god bola!” — Welcoming brighter days with soaring aspirations.',
    themeColor: '#f59e0b',
    gradientBg: 'from-amber-500 via-orange-600 to-rose-700',
    accentBorder: 'border-amber-400/40',
    artMotif: 'kites_sun',
    festivals: [
      {
        name: 'New Year Kickoff',
        dateStr: 'Jan 1',
        tagline: 'Fresh 365-Day Canvas',
        culturalNote: 'Setting financial, health and life resolutions with laser focus.',
        icon: '✨',
      },
      {
        name: 'Makar Sankranti / Pongal / Lohri',
        dateStr: 'Jan 14',
        tagline: 'Kite Festival & Sun Transit into Capricorn',
        culturalNote: 'Sesame & jaggery sweets, colorful sky filled with kites, celebrating winter harvest.',
        icon: '🪁',
      },
      {
        name: 'Republic Day of India',
        dateStr: 'Jan 26',
        tagline: 'Constitution & National Tricolor',
        culturalNote: 'Honoring the democratic constitution, grand parades and national unity.',
        icon: '🇮🇳',
      },
    ],
  },
  {
    monthIndex: 1,
    monthName: 'February',
    heroTitle: 'Mahashivratri & Spring Blossoms',
    heroSubtitle: 'Auspicious meditative energies, awakening consciousness & the bloom of Vasant.',
    culturalQuote: '“Om Namah Shivaya” — Night of deep stillness, introspection and inner spiritual mastery.',
    themeColor: '#6366f1',
    gradientBg: 'from-slate-900 via-indigo-950 to-blue-900',
    accentBorder: 'border-indigo-400/40',
    artMotif: 'shivratri_moon',
    festivals: [
      {
        name: 'Vasant Panchami',
        dateStr: 'Feb 12',
        tagline: 'Worship of Goddess Saraswati',
        culturalNote: 'Celebrating wisdom, music, arts and wearing auspicious yellow attire.',
        icon: '🌼',
      },
      {
        name: 'Maha Shivratri',
        dateStr: 'Feb 16',
        tagline: 'The Great Night of Lord Shiva',
        culturalNote: 'Nightlong meditation, bilva leaves, sacred chanting and inner transcendence.',
        icon: '🌙',
      },
      {
        name: 'Valentine’s Day',
        dateStr: 'Feb 14',
        tagline: 'Celebrating Bonds of Love & Care',
        culturalNote: 'Expressing gratitude for cherished family, partners, and lifelong friends.',
        icon: '💖',
      },
    ],
  },
  {
    monthIndex: 2,
    monthName: 'March',
    heroTitle: 'Holi - The Grand Festival of Colors',
    heroSubtitle: 'Triumph of joy over gloom, vibrant organic powders, sweets & the vibrant equinox.',
    culturalQuote: '“Bura na mano, Holi hai!” — Splashes of vibrant happiness, unity and forgiveness.',
    themeColor: '#ec4899',
    gradientBg: 'from-pink-600 via-purple-600 to-cyan-600',
    accentBorder: 'border-pink-400/40',
    artMotif: 'holi_colors',
    festivals: [
      {
        name: 'Holika Dahan',
        dateStr: 'Mar 23',
        tagline: 'Sacred Bonfire of Purification',
        culturalNote: 'Burning away negativity, ego and welcoming divine protection.',
        icon: '🔥',
      },
      {
        name: 'Rangwali Holi / Dhulandi',
        dateStr: 'Mar 24',
        tagline: 'Festival of Vibrant Organic Colors',
        culturalNote: 'Joyous gulal celebrations, music, gujiya feast and welcoming spring.',
        icon: '🎨',
      },
      {
        name: 'Financial Year End Sprint',
        dateStr: 'Mar 31',
        tagline: 'Tax Planning & Annual Audit Lock',
        culturalNote: 'Finalize 80C investments, NPS contributions and annual financial balancing.',
        icon: '📊',
      },
    ],
  },
  {
    monthIndex: 3,
    monthName: 'April',
    heroTitle: 'Gudi Padwa, Baisakhi & Ram Navami',
    heroSubtitle: 'Traditional New Year dawn, victorious banners, harvest celebrations & new beginnings.',
    culturalQuote: '“Gudi Padvyachya Hardik Shubhechha!” — Auspicious beginnings and prosperous ventures.',
    themeColor: '#ea580c',
    gradientBg: 'from-amber-600 via-orange-600 to-red-700',
    accentBorder: 'border-orange-400/40',
    artMotif: 'harvest_baisakhi',
    festivals: [
      {
        name: 'Gudi Padwa / Ugadi',
        dateStr: 'Apr 9',
        tagline: 'Maharashtrian & Deccan New Year',
        culturalNote: 'Hoisting the auspicious Gudi, neem-jaggery prasad and Shrikhand Puri feast.',
        icon: '🚩',
      },
      {
        name: 'Baisakhi & Vishu',
        dateStr: 'Apr 13',
        tagline: 'Harvest Celebrations Across Punjab & Kerala',
        culturalNote: 'Bhangra beats, golden wheat harvest, and auspicious Vishu Kani reflections.',
        icon: '🌾',
      },
      {
        name: 'Ram Navami & Hanuman Jayanti',
        dateStr: 'Apr 17',
        tagline: 'Virtue, Courage and Righteousness',
        culturalNote: 'Honoring Maryada Purushottam and the epitome of unwavering devotion.',
        icon: '🏹',
      },
    ],
  },
  {
    monthIndex: 4,
    monthName: 'May',
    heroTitle: 'Buddha Purnima & Summer Zenith',
    heroSubtitle: 'Enlightenment, compassion, golden sunshine & mid-year goal check-ins.',
    culturalQuote: '“Peace comes from within. Do not seek it without.” — Mindful focus and serenity.',
    themeColor: '#059669',
    gradientBg: 'from-emerald-700 via-teal-800 to-slate-900',
    accentBorder: 'border-emerald-400/40',
    artMotif: 'buddha_lotus',
    festivals: [
      {
        name: 'International Labour Day & Maharashtra Day',
        dateStr: 'May 1',
        tagline: 'Dignity of Labor & State Heritage',
        culturalNote: 'Celebrating the builders of society and the vibrant legacy of Maharashtra.',
        icon: '🛠️',
      },
      {
        name: 'Mother’s Day',
        dateStr: 'May 10',
        tagline: 'Tribute to Unconditional Love',
        culturalNote: 'Honoring maternal care, family bonds and lifetime support.',
        icon: '🌸',
      },
      {
        name: 'Buddha Purnima',
        dateStr: 'May 23',
        tagline: 'Birth, Enlightenment & Nirvana of Buddha',
        culturalNote: 'Mindfulness meditation, non-violence, and radiating compassion.',
        icon: '🪷',
      },
    ],
  },
  {
    monthIndex: 5,
    monthName: 'June',
    heroTitle: 'International Yoga Day & Monsoon Arrival',
    heroSubtitle: 'Union of body, breath and mind welcoming the lush petrichor of Indian Monsoons.',
    culturalQuote: '“Yogah Karmasu Kaushalam” — Yoga is excellence and mindfulness in every action.',
    themeColor: '#0284c7',
    gradientBg: 'from-blue-600 via-cyan-700 to-emerald-800',
    accentBorder: 'border-cyan-400/40',
    artMotif: 'yoga_monsoon',
    festivals: [
      {
        name: 'World Environment Day',
        dateStr: 'Jun 5',
        tagline: 'Green Planet Stewardship',
        culturalNote: 'Planting saplings, reducing plastic footprint and sustainable living.',
        icon: '🌱',
      },
      {
        name: 'International Day of Yoga & Solstice',
        dateStr: 'Jun 21',
        tagline: '108 Surya Namaskars & Summer Solstice',
        culturalNote: 'Celebrating ancient wellness science, pranayama and inner alignment.',
        icon: '🧘',
      },
      {
        name: 'Monsoon Awakening',
        dateStr: 'Jun 15',
        tagline: 'Petrichor & Lush Green Hills',
        culturalNote: 'Western Ghats waterfalls come alive, warm masala chai and trek planning.',
        icon: '🌧️',
      },
    ],
  },
  {
    monthIndex: 6,
    monthName: 'July',
    heroTitle: 'Guru Purnima & Ashadhi Ekadashi',
    heroSubtitle: 'Reverence for mentors, sacred Wari pilgrimage & devotional monsoon showers.',
    culturalQuote: '“Guru Brahma, Guru Vishnu, Guru Devo Maheshwara” — Saluting teachers and guides.',
    themeColor: '#d97706',
    gradientBg: 'from-amber-600 via-yellow-700 to-stone-900',
    accentBorder: 'border-yellow-400/40',
    artMotif: 'guru_greenery',
    festivals: [
      {
        name: 'Ashadhi Ekadashi / Pandharpur Wari',
        dateStr: 'Jul 17',
        tagline: 'Divine Pilgrimage to Lord Vitthal',
        culturalNote: 'Millions of Varkaris marching with taal-mridang singing abhangas of Tukaram and Dnyaneshwar.',
        icon: '🚩',
      },
      {
        name: 'Guru Purnima',
        dateStr: 'Jul 21',
        tagline: 'Homage to Spiritual & Life Mentors',
        culturalNote: 'Expressing heartfelt gratitude to spiritual guides, teachers and life coaches.',
        icon: '🪔',
      },
      {
        name: 'Income Tax Return (ITR) Filing Deadline',
        dateStr: 'Jul 31',
        tagline: 'Annual Tax Compliance & Verification',
        culturalNote: 'Ensuring seamless tax filings and financial compliance hygiene.',
        icon: '📑',
      },
    ],
  },
  {
    monthIndex: 7,
    monthName: 'August',
    heroTitle: 'Independence Day & Raksha Bandhan',
    heroSubtitle: 'Patriotic spirit, sacred sibling threads & celebratory Krishna Janmashtami festivities.',
    culturalQuote: '“Vande Mataram” — Pride of the motherland and the unbreakable bond of family protection.',
    themeColor: '#f97316',
    gradientBg: 'from-orange-600 via-amber-600 to-emerald-800',
    accentBorder: 'border-orange-400/40',
    artMotif: 'rakhi_tricolor',
    festivals: [
      {
        name: 'Independence Day of India 🇮🇳',
        dateStr: 'Aug 15',
        tagline: 'Celebrating Sovereign Freedom',
        culturalNote: 'Flag hoisting ceremonies, patriotic anthems, and remembering freedom pioneers.',
        icon: '🇮🇳',
      },
      {
        name: 'Raksha Bandhan',
        dateStr: 'Aug 28',
        tagline: 'The Sacred Thread of Sibling Protection',
        culturalNote: 'Sisters tie sacred rakhis, exchanging blessings, sweets and lifelong vows.',
        icon: '🧵',
      },
      {
        name: 'Krishna Janmashtami & Dahi Handi',
        dateStr: 'Aug 30',
        tagline: 'Birth of Lord Krishna & Govinda Pyramids',
        culturalNote: 'High-energy human pyramids breaking the curd pot across Mumbai and Maharashtra.',
        icon: '🦚',
      },
    ],
  },
  {
    monthIndex: 8,
    monthName: 'September',
    heroTitle: 'Ganeshotsav & September Celebrations',
    heroSubtitle: 'Grand Ganpati Bappa arrival, sweet Ukadiche Modaks, and Kaiwalya’s Birthday on 1st Sep!',
    culturalQuote: '“Ganpati Bappa Morya, Pudhchya Varshi Lavkar Ya!” — Divine wisdom, prosperity and birthday milestone.',
    themeColor: '#f59e0b',
    gradientBg: 'from-amber-600 via-orange-600 to-purple-900',
    accentBorder: 'border-amber-400',
    artMotif: 'ganesh_birthday',
    festivals: [
      {
        name: "Kaiwalya's Birthday 🎂",
        dateStr: 'Sep 1',
        tagline: 'Personal Milestone Celebration & VIP Birthday',
        culturalNote: 'Celebrating life, achievements, annual goals reset, special dinners & cake cutting!',
        icon: '👑',
        isPersonalMilestone: true,
      },
      {
        name: 'Teachers’ Day & Engineers’ Day',
        dateStr: 'Sep 5 & 15',
        tagline: 'Honoring Gurus & Sir M. Visvesvaraya',
        culturalNote: 'Saluting educators, mentors, and the architects of technology and infrastructure.',
        icon: '📐',
      },
      {
        name: 'Ganesh Chaturthi / Ganeshotsav 🌺',
        dateStr: 'Sep 14',
        tagline: 'Grand 10-Day Festival of Lord Ganesha',
        culturalNote: 'Welcoming the Vighnaharta with dhol-tasha, modaks, illuminated pandals, and joyous aarti.',
        icon: '🐘',
      },
      {
        name: 'Anant Chaturdashi (Ganesh Visarjan)',
        dateStr: 'Sep 24',
        tagline: 'Grand Farewell & Blessings Immersion',
        culturalNote: 'Massive celebratory processions with gulal, rhythmic drums, and emotional farewell.',
        icon: '🌺',
      },
      {
        name: 'Onam Harvest Festival',
        dateStr: 'Sep 15',
        tagline: 'King Mahabali’s Homecoming & Onasadya',
        culturalNote: 'Grand 26-dish feast, intricate flower carpets (Pookkalam) and snake boat races.',
        icon: '🌸',
      },
    ],
  },
  {
    monthIndex: 9,
    monthName: 'October',
    heroTitle: 'Navratri, Durga Puja & Vijayadashami',
    heroSubtitle: 'Nine sacred nights of rhythmic Garba, divine feminine power & triumph of light at Dussehra.',
    culturalQuote: '“Shubh Dussehra!” — Victory of good over evil, crossing boundaries into new conquests.',
    themeColor: '#ec4899',
    gradientBg: 'from-fuchsia-700 via-rose-700 to-indigo-900',
    accentBorder: 'border-fuchsia-400/40',
    artMotif: 'navratri_dussehra',
    festivals: [
      {
        name: 'Gandhi Jayanti',
        dateStr: 'Oct 2',
        tagline: 'International Day of Non-Violence',
        culturalNote: 'Reflecting on truth (Satya), simplicity and self-reliance.',
        icon: '🕊️',
      },
      {
        name: 'Navratri & Durga Puja Grand Festivities',
        dateStr: 'Oct 11 - 19',
        tagline: '9 Nights of Garba, Dandiya & Dhunuchi Dance',
        culturalNote: 'Vibrant ethnic attire, twirling ghagras, energetic beats and Goddess Durga veneration.',
        icon: '🪘',
      },
      {
        name: 'Dussehra / Vijayadashami',
        dateStr: 'Oct 20',
        tagline: 'Triumph of Lord Rama & Simolanghan',
        culturalNote: 'Effigy burning of Ravana, exchanging Apta leaves (Sone / Gold) for eternal fortune.',
        icon: '🏹',
      },
    ],
  },
  {
    monthIndex: 10,
    monthName: 'November',
    heroTitle: 'Diwali - The Grand Festival of Lights',
    heroSubtitle: 'Glowing earthen diyas, Dhanteras prosperity, sweet Faral feasts & sparkling fireworks.',
    culturalQuote: '“Shubh Deepavali!” — May your wealth, health, and happiness shine with boundless luster.',
    themeColor: '#eab308',
    gradientBg: 'from-amber-500 via-orange-600 to-yellow-700',
    accentBorder: 'border-yellow-300',
    artMotif: 'diwali_diyas',
    festivals: [
      {
        name: 'Dhanteras & Gold Buying',
        dateStr: 'Nov 6',
        tagline: 'Lord Dhanvantari & Prosperity Invocation',
        culturalNote: 'Purchasing precious metals, gold coins, new utensils, and invoking abundance.',
        icon: '🪙',
      },
      {
        name: 'Narak Chaturdashi & Abhyanga Snan',
        dateStr: 'Nov 8',
        tagline: 'Early Dawn Ubtan & Fragrant Bath',
        culturalNote: 'Fragrant utna scrub at dawn, bursting crackers and enjoying homemade Diwali faral.',
        icon: '✨',
      },
      {
        name: 'Lakshmi Pujan & Chopda Pujan',
        dateStr: 'Nov 8',
        tagline: 'Grand Goddess Lakshmi Worship & Muhurat Trading',
        culturalNote: 'Auspicious financial books blessing, diyas lighting every corner, Muhurat stock picks.',
        icon: '🪔',
      },
      {
        name: 'Diwali Padwa & Bhai Dooj (Bhau Beej)',
        dateStr: 'Nov 10',
        tagline: 'Husband-Wife Bonds & Sibling Feast',
        culturalNote: 'Special gifts, aarti for brothers, delicious basundi puri feasts.',
        icon: '🎁',
      },
      {
        name: 'Guru Nanak Jayanti (Gurpurab)',
        dateStr: 'Nov 15',
        tagline: 'Birth of Guru Nanak Dev Ji',
        culturalNote: 'Prabhat Pheris, Nagar Kirtan, and community Langar of unconditional service.',
        icon: '☬',
      },
    ],
  },
  {
    monthIndex: 11,
    monthName: 'December',
    heroTitle: 'Christmas Cheer & New Year Countdown',
    heroSubtitle: 'Twinkling festive pine trees, holiday season warmth, year-end retrospective & celebrations.',
    culturalQuote: '“Merry Christmas & A Prosperous New Year!” — Counting blessings, gearing up for tomorrow.',
    themeColor: '#dc2626',
    gradientBg: 'from-red-700 via-emerald-800 to-slate-950',
    accentBorder: 'border-red-400/40',
    artMotif: 'christmas_stars',
    festivals: [
      {
        name: 'Winter Solstice',
        dateStr: 'Dec 21',
        tagline: 'Shortest Day & Cozy Winter Nights',
        culturalNote: 'Cozy evenings, warm beverages, and beginning of expanding sunlight.',
        icon: '❄️',
      },
      {
        name: 'Christmas Eve & Day',
        dateStr: 'Dec 24 - 25',
        tagline: 'Joy, Caroling & Plum Cake Feasts',
        culturalNote: 'Decorating festive trees, secret Santa gift exchange, festive holiday spirit.',
        icon: '🎄',
      },
      {
        name: 'New Year’s Eve Grand Finale',
        dateStr: 'Dec 31',
        tagline: '365 Days of Triumphs & Countdown Fireworks',
        culturalNote: 'Celebrating all personal financial, health, and habit milestones of the year.',
        icon: '🎆',
      },
    ],
  },
];
